### ISSUE TITLE
Prepare for Stages & Status Migration

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/digital-platform#1002]
**Background**
In order to migrate data to the new Stages & Statuses, some checks need to be run and updates need to be made.

**User Story** 
As the Digital team, I would like to check historic instances of status usage and map some previous statuses to new statuses so that data can be migrated.

**Feature(s) Description** 

- Run a script to obtain data regarding all instances of historic stages and statuses
  - i.e. Look at all `applicationRecords` and count up each and every status and stage that exists. This will tell us which statuses are being used and might highlight statuses we weren't aware of
  - See comment below for details of an existing script which does this
- Share data with Nick
  - We are interested in all stages and statuses that are being used and in particular: 1. ‘submitted first test’, 2. ‘test submitted over time’, and 3. ‘submitted scenario test’ statuses
- Using the mappings identified in the spreadsheet and along with feedback from the above data write up a final set of migration 'mappings' (either documented as text, in a spreadsheet or in code - perhaps as a set of unit tests). For example:
  - Map any instances of ‘submitted scenario test’ statuses to 'scenario test failed’
  - Map any instances of ‘Rejected as ineligible' status to 'Ineligible (ASC) -Rejected

[Application Stages and Statuses Versions.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdb88aa6b44ba3b7cda1d79ca02df831b3eb013b/Application%20Stages%20and%20Statuses%20Versions.xlsx)

**Note**
- The actual migration script is written, tested and run in ticket #997 (though we can make a start here if we like)
- Updating Admin and DP with the newly named statuses (and removing some) is covered by jac-uk/admin#2294

**Definition of Done (optional/delete if not used)**
It's done when we are ready to test the new stages & statuses on several historic exercises.

**User Testing Steps**
Add instructions here

**Ticket Champion**
Warren

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/1002?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by nickaddy** [comment]
@HalcyonJAC @warrensearle This is the pre-migration work to do ahead of writing the migration script, ideally this is ticket 1/3 with the other two the existing tickets. Pls check with Matt if any of above unclear as I will be out of office tues and wednesday.

**Comment by warrensearle** [comment]
Hey there I think the main work in this ticket is to produce a spreadsheet to identify and provide a count of all the statuses (and stages) used across all `applicationRecords`. The writing of the actual migration script (and execution of it) is covered by another ticket #997

We do have a node script which pretty much does this already (amongst other things):
https://github.com/jac-uk/digital-platform/blob/2ded89da0f3043cfc2b8ab7958dc739896e0b7e0/nodeScripts/query.exercise-applications.js#L26-L40

Once this data has been reviewed then the rules for status (and stage) updates can be finalised.

**Comment by HalcyonJAC** [comment]
- submittedFirstTest: 0 application records
- testSubmittedOverTime: 48 application records
- submittedScenarioTest: 7 application records
- rejectedAsIneligible: 609 application records

**Comment by warrensearle** [comment]
Thanks @HalcyonJAC I have just updated this ticket with the changes we discussed last week. The numbers above look good however could you provide a full set of numbers for the statuses used in all applications - just in case there are some using statuses we aren't already aware of

**Comment by HalcyonJAC** [comment]
I have created a node script `query.applications-stages-statuses.js` to query the number of applications and application records, stages, and statuses of all exercises.

_**Update: 29/01/2024 11:00:00**_ 

applications
- total: 34720
- applied: 23798
- draft: 10171
- withdrawn: 750
- undefined: 1

applicationRecords
- total: 24780
- review: 15050
- shortlisted: 2788
- recommended: 498
- selected: 3406
- handover: 3036
- undefined: 2

status
- failedFirstTest: 6477
- failedScenarioTest: 3056
- '': 939
- passedSelection: 503
- invitedToSelectionDay: 1117
- passedFirstTest: 354
- failedSift: 2610
- failedSelection: 2227
- approvedForImmediateAppointment: 3034
- noTestSubmitted: 2049
- withdrewApplication: 602
- passedButNotRecommended: 130
- rejectedAsIneligible: 609
- criticalAnalysisPassed: 515
- passedSift: 110
- situationalJudgementPassed: 291
- testSubmittedOverTime: 48
- passedScenarioTest: 5
- rejectedByCharacter: 34
- situationalJudgementFailed: 23
- submittedScenarioTest: 7
- noScenarioTestSubmitted: 19
- approvedForFutureAppointment: 12
- undefined: 2
- criticalAnalysisFailed: 5
- sccToReconsider: 2

**Comment by warrensearle** [comment]
Awesome, thanks @HalcyonJAC

**Comment by nickaddy** [comment]
@HalcyonJAC Can you pls run a report that picks up these instances along with exercise details (name, ref, SET contacts and candidate refs? •	testSubmittedOverTime: 48 application records

**Comment by nickaddy** [comment]
@HalcyonJAC I think this is more or less complete; can you just provide the details of apps, app records and statuses that are undefined for completeness?
