### ISSUE TITLE
Bug: Handover report not being created

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#1056]
Please see the handover report on exercise JAC00117.

**Expected**
Press the refresh button and see the latest report available on screen and for download

**Actual**
Press the refresh button and the page shows an error and the report is not available on screen or to download

**Error**
Looking at the cloud function logs we can see the following error which indicates the report is too big for firestore (the max size of one firestore document is 1MB)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei95QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e84dabe1f5ebdc1854260c59182c451e975eafa5/image.png" alt="image.png" />

Please look at reducing the size of the report - 1MB is a lot! Alternatively look to store the report elsewhere or indeed not store it anywhere, just have it as a downloadable file (or json response).

**Comment by HalcyonJAC** [comment]
I have generated the handover report for Exercise 117 manually and sent it to Sam. Sam had another requirement which was to separate the additional working preferences into different columns. I updated the node script to do so but didn't commit to the codebase as it was just for exercise 117.

**Comment by warrensearle** [comment]
Thank you @HalcyonJAC. Yes the Additional working preferences column needs some attention! We shouldn't have the questions duplicated in one column on every row. It should be as Sam has requested with one column per question.
