### ISSUE TITLE
Upgrade to use latest version of Node on Digital Platform

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/digital-platform#1091]
## Requirement
- [x] Upgrade our Digital platform code base to use the latest version of Node. In particular firebase functions should run in a newer version of node (e.g. 18 or 20 or newer). See here for more info: https://firebase.google.com/docs/functions/manage-functions?gen=2nd#set_nodejs_version
- [x] Upgrade firebase/functions package to latest version
- [x] Upgrade firebase/admin package to latest version

**Comment by KoWeiJAC** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/1091?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle
