### ISSUE TITLE
Clean Data On Develop

### ISSUE THREAD

**Issue by drieJAC** [jac-uk/digital-platform#1132]
## Background
Data in the Develop database is mostly out of date and can cause warnings/errors to display where they shouldn't.

## User Story
As a developer/tester I want to have an accurate set of data to test with on Develop

## Feature(s) Description
1. Backup develop db
2. Clear existing data on develop using nodescript  => empty the collections but leave the collections themselves there.

applicationRecords
applications
applications_temp
assessments
bugReports
candidateForms
candidates
customReports
exercises
exercises_temp
invitations
messages
notes
notifications
panellists
panels
userInvitations
vacancies
meta (change counts to 0)

3. Can we also empty all of the collections with '_deleted' at the end of their names?
4. Create sample exercises for (legal, non-legal, leadership, leadership non-legal) and add the following to their name ‘TEMPLATE - DO NOT EDIT’. These will become templates which can easily be copied to initialise new exercises.

**Comment by tomlovesgithub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/1132?planning-poker) with Zenhub @drieJAC @HalcyonJAC

**Comment by KoWeiJAC** [comment]
Backup files on Google Cloud Storage: https://console.cloud.google.com/storage/browser/digital-platform-develop-backups/firestore/2024-08-27T22:01:13.343Z

**Comment by HalcyonJAC** [comment]
Note: The data on Dev has been cleaned out.

**Comment by nickaddy** [comment]
@HalcyonJAC Can this ticket be closed now? I think we need to add some generic data to the templates, but that can be done separately.
