### ISSUE TITLE
Convert Functions from CommonJS to ESM

### ISSUE THREAD

**Issue by HalcyonJAC** [jac-uk/digital-platform#1165]
## Background
The ticket aims to convert functions in digital-platfrom from CommonJS to ESM to reuse the code from admin and jac-kit.

## User Story
As the Digital team, I would like to use ESM in digital-platform.

## Feature(s) Description
- [ ] Convert from CommonJS to ESM.
- [ ] Update all functions to use `import`/`export` instead of `require`/`module.exports`
- [ ] Ensure all the tests pass. 

## Acceptance Criteria 
Specify the requirements of the primary user(s) for the change, update, or new feature - use the format: 
It's done when...

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Internal testing only.

**Comment by nickaddy** [comment]
@HalcyonJAC Pls check in with Warren on Thursday regarding this ticket.
