### ISSUE TITLE
SPIKE Research If It's Possible To Run a report of commonly requested custom reports

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/digital-platform#1209]
## Background
We are currently reviewing the selectable fields on the custom report to see how we can make it more user friendly and ensure that it is being used for specific purposes rather than to replace existing report data; we aim to reduce the number of required data fields in the custom report that are already present in existing reports.

## Features

- [x] Investigate if it'spossible to produce a report showing which fields users have been selecting in the custom report during all 2024 to date, to help identify what are the commonly used fields and what are the most requested custom reports

** If the spike is successful then we will need a new ticket to actually do the work **

## Acceptance Criteria 
It's done when we have worked out if the data is available

## Feature Champion
Matt

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/1209?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by drieJAC** [comment]
@warrensearle @tomlovesgithub @HalcyonJAC Where does the data come from for this report, ie telling us the fields used?

**Comment by warrensearle** [comment]
@drieJAC we _might_ be able to grab data from Google Cloud Logs but I think this might take a decent amount of effort.

Alternatively we could more easily provide a report on the saved reports only... which is not what this ticket is asking for but is the easiest way to get an indication of what our users find valuable. See 'Save Report' button:
<img width="1454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeElWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fc801ea7ebaa5f7530a2a633f45d11382873937/image.png" alt="image.png" />

**Comment by warrensearle** [comment]
@NormaJAC I have estimated based on providing you a report on common fields in our users' saved reports. i.e. this won't include data for users who create a report from scratch each time and do not save it. Will this be acceptable to you?

**Comment by nickaddy** [comment]
@warrensearle I've tested the Save report feature and it doesn't work for me, i.e. I am not able to save a custom report. Does it work for you?

**Comment by warrensearle** [comment]
@nickaddy ha, oh dear, I assumed it worked! No it doesn't work for me.

I was just sticking my oar in as I'm not sure we are collecting the data that is needed to provide the data requested in this ticket. The following needs investigating (and maybe other ideas) but if none come up trumps then we may need to re-think this task:
 - Check whether Cloud Logs contain the information requested
 - Check whether usage of the custom report is tracked in our own Event log
 - Check whether anyone has saved reports (it's currently broken functionality but may have worked in the past and only recently broke)

**Comment by NormaJAC** [comment]
@warrensearle yes, that's acceptable because we just want to know what the commonly selected fields are so that we can whittle them down.

**Comment by NormaJAC** [comment]
@warrensearle @nickaddy the 'save report' button doesn't work for me too, nothing happened when I clicked on save <img width="1475" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhpQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--372a599669b241cf5a47954bc31cfd3d1abfe812/image.png" alt="image.png" />

**Comment by warrensearle** [comment]
Hey @NormaJAC I have looked at the code and the Save custom report button did work in the past. On production we have 108 saved custom reports. From these we could indeed run a quick report to present you with the fields being searched for and their frequency.

If you'd like us to do this please let us know (this ticket suggests a new ticket will be created) and then close this ticket.

**Comment by NormaJAC** [comment]
@warrensearle Do the108 saved custom reports include any from 2024?

**Comment by warrensearle** [comment]
Hey @NormaJAC good question. Sadly we don't store the date the reports were saved so I can't answer that question. The names of the reports might give some indication (e.g. there are quite a few where the name indicates they are for ex 129). I can confirm too that the reports do get saved when the user presses the Save button... there's just a bug from that point onwards (seeing the save has worked and loading a saved report)

**Comment by nickaddy** [comment]
@warrensearle Can you clarify where the reports are saved and what the idea was behind this feature? I had imagined it might allow users to create a commonly used set of fields and then apply it to a selected exercise...

**Comment by NormaJAC** [comment]
@warrensearle I'll create a separate ticket as required, thanks

**Comment by warrensearle** [comment]
> @warrensearle Can you clarify where the reports are saved and what the idea was behind this feature? I had imagined it might allow users to create a commonly used set of fields and then apply it to a selected exercise...

@nickaddy the reports are in the `customReports` collection and yes that's exactly the intention of this feature. Within the saved reports some are generic - e.g. 'Welsh questions' - though others have been given exercise-specific titles - e.g. '129 Eligibility (minus PQE)'. So it's a bit of a mixed bag!

**Comment by nickaddy** [comment]
@warrensearle So where would the users access the report?

**Comment by NormaJAC** [comment]
New ticket: https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/digital-platform/1228
