### ISSUE TITLE
Provide a report of saved custom reports

### ISSUE THREAD

**Issue by NormaJAC** [jac-uk/digital-platform#1228]
## Background
We are currently reviewing the selectable fields on the custom report to see how we can make it more user friendly and ensure that it is being used for specific purposes rather than to replace the existing reports; we aim to reduce the number of data fields in the custom report that are already present in existing dedicated reports (diversity, handover, reasonable adjustments etc) on the platform and add any missing fields that are relevant to each exercise.

Once we identify commonly used fields we can update the custom report on the platform by removing redundant fields and adding missing fields making the reports more relevant to the exercise. From [the previous ticket](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/digital-platform/1209), we are aware that there are 108 saved custom reports on Production and we are hoping these can be used to produce the required data.

## User Story
As the Digital team, we would like to see a report containing the saved report data so that we can identify commonly used fields.

## Feature(s) Description

- [ ] Produce a user-friendly report showing the data (columns) saved in custom Reports to aid in the above task

## Acceptance Criteria
- [ ] The report should be formatted in a way that allows us to clearly see which fields are commonly used in the custom report

## Feature champion
Norma

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/1228?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle
