### ISSUE TITLE
2FA - Set Up SMS Service

### ISSUE THREAD

**Issue by drieJAC** [jac-uk/digital-platform#1231]
### This ticket is part of the following epic: https://github.com/jac-uk/apply/issues/1220

As part of implementing 2FA we would like to be able to send SMS messages from the digital platform.

## User Story
Investigate SMS options and  set up a function which calls the SMS servce.

## Definition of Done
- [x] Investigate different pricing options of using the Google service or the GovUK Notify service
- [ ] Create a frontend function which calls the firebase sms service with a mobile number and returns a response indicating success or failure

**Comment by drieJAC** [comment]
After discussions with @warrensearle we will try using firebase's built-in service

**Comment by HalcyonJAC** [comment]
Pricing of Firebase built-in SMS service

<img width="765" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xpQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5633875baacfc22dc4d558c75f2a96722ce90fc6/Screenshot%202024-10-22%20at%2011.22.36.png" alt="Screenshot 2024-10-22 at 11.22.36.png" />
