### ISSUE TITLE
Create a new Vue application

### ISSUE THREAD

**Issue by ollietreend** [jac-uk/digital-platform#133]
With boilerplate for:

- jest tests
- Firebase SDKs
- maybe Vuex
- probably Vue Router

**Comment by tatyree** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Untitled card](https://trello.com/c/x87qWLzy/1-untitled-card)

**Comment by tatyree** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QT handling application sign-in page](https://trello.com/c/x87qWLzy/1-qt-handling-application-sign-in-page)

**Comment by tatyree** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a candidate, I can see a link to the form for the QT I am about to take](https://trello.com/c/11wOop8A/5-as-a-candidate-i-can-see-a-link-to-the-form-for-the-qt-i-am-about-to-take)
