### ISSUE TITLE
Refine data models, improve variable names and fix typos

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#248]
Here we should identify and consider ways to improve our data models, including how we group data and name variables.

In addition let's list here any known issues. We should consider best approach to fix them (or not).

- [ ] `characterInformation.diciplinaryActionOrAskedToResign` is mis-spelt. should be '...disciplinary...'
- [ ] `characterInformation.diciplinaryActionOrAskedToResignDetails` is mis-spelt. should be '...disciplinary...'
- [ ] `equalityAndDiversitySurvey.changedGender` has reversed polarity! It should be called something like `genderSameAsAtBirth`
- [ ] `application.feePaidOrSalariedSatForThirtyDays` needs to be changed! this field now indicates weather the custom amount of days has been sat ,something like `feePaidOrSalariedSatForMinDays`

A data model spreadsheet can be found here: 
https://docs.google.com/spreadsheets/d/1JVe74eHM9-fDXvSfrOCuItpK6VN2q63skELCVm3S_Eo/edit#gid=240172058

**Comment by YaaL** [comment]
Membership fields are currently flat in application.
Should organise them under `memberships`.

Fields like:

- `charteredAssociationBuildingEngineersDate`
- `charteredAssociationBuildingEngineersNumber`
- `charteredInstituteBuildingDate`
- `charteredInstituteBuildingNumber`
- `charteredInstituteEnvironmentalHealthDate`
- `charteredInstituteEnvironmentalHealthNumber`
- ...

**Comment by warrensearle** [comment]
Exercise open and close dates are stored without the time. Let's consider storing the time too - which for now is always 13:00.

**Comment by warrensearle** [comment]
Lets split `application.referenceNumber` into it's two parts:
- `exercise.referenceNumber`
- Unique random code

This means we can then search the code independently of exercise ref
