### ISSUE TITLE
SPIKE: File Storage. Choose most suitable tech stack

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#256]
We share and receive files via our various apps (admin, apply, assessor). 
Currently the files are stored in Firebase Storage.
We need to ensure security, manage who has access and protect against viruses.

We should consider:
- Continuing with a firebase storage only tech stack
- Using google drive as well / instead
- Virus scanning
- Managing access

**Comment by KateMJAC** [comment]
@warrensearle does this still need completing?
