### ISSUE TITLE
Refine database security rules and write more tests

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#257]
We have a base set of database security rules however there is scope to be more granular and tighten the security further.

**Comment by warrensearle** [comment]
Have applied an initial estimate of 13 as this is a fairly big piece of work.

**Comment by warrensearle** [comment]
Firestore rules now support locking down the fields that can be added and edited. 
See here: https://firebase.google.com/docs/firestore/security/rules-fields
This means we could include model validation which would be nice.

There is a related piece of work to implement User Roles, which will result in us having a `role` in the auth token (custom claims). When this has been implemented it is suggested the firestore and storage rules should be re-written. See #285. I suggest we get that rolled out before spending too long refining rules now which will then be re-written.

**Comment by HalcyonJAC** [comment]
OK - this has some updates. I've added the firestore emulation and some tooling to import and export the data as we need and added some basic validation rules which work against the app running against the local firestore emulator. Its now restricting creation of documents without required attributes.

As the user roles progress - this will need to be extended.
