### ISSUE TITLE
Refine storage security rules and write tests

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#258]
We have basic storage security rules but these do not have tests so we need to tighten up the rules and write a decent set of tests.

Some of the rules that need to be implemented are:

- [x] Restrict file types
- [x] Restrict file size
- [ ] _tbc_

**Comment by warrensearle** [comment]
The rules to restrict file size and type have been addressed in other tickets. Wrapping in unit tests would be good, if it doesn't take too long to figure out how to set up the test - hopefully it's along the lines of the `setup` and `teardown` helpers we have for our firestore rules tests.

**Comment by londonprojects** [comment]
This issue need to be reviewed
