### ISSUE TITLE
Handle custom exercise open and close times

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#274]
Currently we have a scheduled function running at 13:00 each day to process any exercises opening or closing that day.

This approach will need to be modified so we can support custom open/close times. 

One alternative approach is to make use of [Cloud Tasks](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=16&ved=2ahUKEwi7seORmNvoAhVHQUEAHS0aCsoQFjAPegQIDBAQ&url=https%3A%2F%2Fcloud.google.com%2Ftasks&usg=AOvVaw3tAsKCESX4lrWgRs48sJ4E). This enables us to perform an action in the future at a custom time. We can update and cancel these tasks - for example if the exercise is cancelled or the open/close date is changed.

Note: We could also provide a UI for admins to modify & cancel cloud tasks.

**Comment by Rebecca-mcknight1991** [comment]
@Rebecca-mcknight1991 think about this.
