### ISSUE TITLE
New cloud function to export applications documents

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/digital-platform#279]
Is your feature request related to a problem? Please describe.

As an admin user
I want to the platform to create and store candidate information in one place
So that I can easily collate the information for panels and move their information to the relevant panels folder on google drive

Describe the solution you'd like
I want the platform to automatically create a google drive for my exercise and store the following in there:

Candidate Assessment
Candidate CV (if applicable)
Independent Assessments

Describe alternatives you've considered
Combining all these documents into one document automatically.

Additional context
We would like to use Google drive for this. We would like the platform to create the folder/drive for the exercise and store the candidates information is stored in subfolders if possible

**Comment by YaaL** [comment]
Sheets API: https://developers.google.com/sheets/api/quickstart/js

**Comment by KateMJAC** [comment]
superseded by Epic #410 and currently being progressed.
