### ISSUE TITLE
Populate candidate records with applications count

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#289]
We need to include a count of applications in our candidate records. This will be displayed, for example, in the admin Candidate List (see admin#509).

**Data model**
The suggested data model for this is to update the Candidate documents to have:
`applications: {
  draft: Number,
  applied: Number,
}`

**To do**
This task is about pulling existing data into the candidates documents so that candidates can be listed
- [x] Populate `applications.applied`
- [x] Populate `fullName`

We have a separate task to ensure our summary data stays up to date

**Note** 
We may include `withdrawn` in the data model but this isn't necessary right now and will need consideration. Such as whether this impacts our `applied` count. Right now `applied` will not decrease if the candidate withdraws their application.

**Comment by warrensearle** [comment]
Whilst we're at it let's store `fullName` here too. Or at least a copy of it. 
This then gives us a thin parent collection, for more efficient listing purposes, with data stored in sub-collection document(s).
We will (re)consider this data model approach in digital-platform#248

**Comment by warrensearle** [comment]
This issue was referenced by admin#703.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle is this so admin can see number of applications when they look at a list of candidates?

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 yes it is... there are a few tickets related to this and I suspect displaying an application count might not actually be as important as other tasks - e.g. candidate search

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle yes I don't think we need it. We need the counter on the exercise overview to be accurate but other than that I think we can drop other related tickets.

**Comment by warrensearle** [comment]
Contrary to my comments above this is closely coupled with the global candidate search functionality: we need to maintain an index of names in our `candidates` collection and can for little/no cost also include a count of applications.
