### ISSUE TITLE
sendCharacterCheckRequests should actually send an email to the candidate

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#292]
Callable function `sendCharacterCheckRequests` should actually send an email to the candidate.

This is blocked until the Notify template has been created. FYI @ClaireTroughtonJAC.

**Comment by Rebecca-mcknight1991** [comment]
@Rebecca-mcknight1991 chase.

**Comment by Rebecca-mcknight1991** [comment]
FIND THE TEMPLATE
