### ISSUE TITLE
Enable multiple devs to work on firebase config

### ISSUE THREAD

**Issue by lloback** [jac-uk/digital-platform#295]
Our firebase config is hosted in the cloud, accessed via firebase and google cloud consoles.

This task is to bring our config files into source control in such a way that:
- code is testable
- we have a base-line set of tests
- code changes are managed via PR with peer approval
- deployment is part of CI pipeline

An initial attempt was made to achieve this in digital-platform repo however the code there contains lots of redundant & historic code, is not very test friendly and not particularly well organised. See #275.

**Comment by KateMJAC** [comment]
Hello @warrensearle how is this ticket coming along?

**Comment by warrensearle** [comment]
Hey @KateMJAC the bulk of this ticket is done - it just needs rolling out when the current code freeze has ended.

**Comment by KateMJAC** [comment]
Hello @warrensearle has this been rolled out? if not can we?
