### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by lloback** [jac-uk/digital-platform#300]
This task was created after a [Miro Tech Brain Debt](https://miro.com/app/board/o9J_kqELX-M=/).

We need a way of logging some actions on the systems: Who/When, at least with critical actions

#260 is related

Might want to use https://www.npmjs.com/package/winston or something similar in the front-end which lets log to different destinations so we could simultaneously log some things to db, slack, dev dashboard etc.

**Comment by KateMJAC** [comment]
Assigned to Halcyon's March WO.

**Comment by HalcyonJAC** [comment]
Hi

Here is a suggested specification for this component:

- Create a logging component that can be used to log events to the database.
- The component will be part of the JAC Kit, with a common interface that enables it to be used by the Digital Platform and the Admin, Apply and Assessments front-end applications.
- Events will have an event type: i.e. Info, Error, Warning, etc.
- User ID will be recorded, or will be NULL if the event relates to a system-generated action.
- Each event can optionally be sent to an external source, i.e. Slack.

Possible future enhancements:

- Ability to publish events to other mediums/channels (i.e. other than the database and Slack).
- Ability to limit the amount of history that is retained in the database event log. Note: This could be a simple system-wide setting or could be implemented by event type, i.e. if certain types of events should be retained for longer than others.
- A notifications dashboard within the Admin platform. Users would subscribe to some (or all) types of events in the system and receive notifications for events they are subscribed to / interested in.
