### ISSUE TITLE
Spike: Build branches to separate dev environments

### ISSUE THREAD

**Issue by lloback** [jac-uk/digital-platform#303]
Task created from a [Miro Tech Brain Dump](https://miro.com/app/board/o9J_kqELX-M=/).

This spike is to discuss the need for separate branches for the dev environments.

https://about.gitlab.com/stages-devops-lifecycle/review-apps/
https://vercel.com/
Use firebase emulator suite?

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.

**Comment by warrensearle** [comment]
The spike part of this task was already done and we have now rolled out Feature Previews for all Pull Requests.

This means that whenever a Pull Request (PR) is created, or updated, a unique url is created and allows the user to preview the app with those changes included.

This has the following benefits:
 - Developers can view & test changes without needing to deploy the code locally
 - Product Owner can view & test changes and feedback much earlier in our workflow
 - User testing can happen before the changes have been merged into our main codebase
 - We can simplify our codebase and release strategy (Git Flow -> Github Flow)

**Comment by warrensearle** [comment]
@KateMJAC please close this ticket when you are happy with the feature previews
