### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by lloback** [jac-uk/digital-platform#305]
Created from a [MIro Tech Brain Dump](https://miro.com/app/board/o9J_kqELX-M=/)

We need the creation a Pull Request template, with the information that we want on it, and added to git.

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.

**Comment by warrensearle** [comment]
This has been rolled out to Admin and Apply repos.

To review please view the following template:
https://github.com/jac-uk/apply/blob/develop/.github/pull_request_template.md

PR authors will fill in the blanks and delete parts as appropriate.

Note: this is a starter-for-ten and the template should be refined over time to be as useful as possible to all stakeholders/reviewers.
