### ISSUE TITLE
Move Virus Scanning function into Digital Platform

### ISSUE THREAD

**Issue by crablab** [jac-uk/digital-platform#311]
Move into and document the Virus Scanning function in the Digital Platform repository. 

We should also ensure we can deploy this from `digital-platform` as with the other functions. 

My suggestion is this should go in a new directory: `functions/virus-scanning` 

@warrensearle Can I confirm this is okay with you?

**Comment by warrensearle** [comment]
This is done and merged now so closing this issue.
Deployment work is covered by #295
