### ISSUE TITLE
Move Virus Scanning GAE Container into Digtial Platform

### ISSUE THREAD

**Issue by crablab** [jac-uk/digital-platform#312]
The virus scanning relies on a GAE Docker Container to actually carry out the scan of the file. We should create a new directory within Digital Platform `digital-platform` to hold GAE containers (as we'll have more in future!)

For now, we can deploy this manually and we'll look at automating that deployment once I have a better idea how the Digital Platform repository works at the moment. We'll document this alongside the container code.

**Comment by warrensearle** [comment]
This is done and merged so closing this issue. 
Deployment work is covered by #295
