### ISSUE TITLE
Restrict size and type of files that can be uploaded

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#327]
Currently there are no restrictions on the file types we allow to be uploaded.  We need to restrict this to

docx, txt, pdf, .odx

Note the same restrictions are added to the UIs of our apps:
- Admin admin#206
- Apply apply#330
- Assessments assessments#42

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle is this done?

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 no this has not been implemented yet

**Comment by HalcyonJAC** [comment]
@warrensearle I have had a quick scan of the code in the Digital Platform repo and I can't see any 'upload file' functionality in it.

The only thing I found relating to files was a `google-drive.js` file. It contains a `createFile()` function but there is no `uploadFile()` function or anything like that. 

Perhaps I'm looking in the wrong place...

I think I need to understand how the Digital Platform repo is involved in the upload process.

Please advise

Darrel

**Comment by HalcyonJAC** [comment]
- [ ] Check what file types should be allowed
- [ ] Check what is currently allowed and update the code to match the above
  - [ ] Admin portal
  - [ ] Apply portal
  - [ ] Assessment portal
- [ ] Restrict storage rules in the Digital Platform itself

**Comment by HalcyonJAC** [comment]
Development Plan:

- [ ] Update the code so that only correct file types and sizes are allowed:
  - [ ] Admin portal
  - [ ] Apply portal
  - [ ] Assessment portal
  - [ ] Digital Platform (storage rules)

**Comment by joy-ade** [comment]
@KateMJAC  and @warrensearle   are you content with this please?

**Comment by joy-ade** [comment]
@HalcyonJAC I can confirm the requirement is Digital platform. Admin portal, Apply portal and Assessment portal is out of scope for this requirement. Can you create a ticket that capture Apply portal, Admin portal and Assessment portal this will be worked on, on a later date.

**Comment by HalcyonJAC** [comment]
As discussed with @warrensearle the changes made to Digital Platform (storage rules), JAC Kit and Admin portal can go live once they have passed code review. However, the changes made to the Apply and Assessment portals should be shelved for now as having them use the JAC Kit in general is part of a bigger ticket.

**Comment by KateMJAC** [comment]
Hello @HalcyonJAC this ticket is part of the Handling Files and Virus scanning epic. I'm guessing that work on the files size and type doesn't really address risks associated with malware? 

We'll get that on the RM if not.
