### ISSUE TITLE
Issues report should be stored on applicationRecords rather than applications

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#328]

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle do we need this now?

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 yes this is needed and will need to be done in order to finish off Eligibility & Character Issues

**Comment by warrensearle** [comment]
This is also needed for the Statistics epic so have prioritised accordingly.
