### ISSUE TITLE
Copy new "independentAssessmentsHardLimit" field to assessments

### ISSUE THREAD

**Issue by crablab** [jac-uk/digital-platform#334]
In the function where we create assessments, we should also copy over the `exercise.independentAssessmentsHardLimit` as `assessment.hardLimit`, where the former exists (optional field).

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle do we still need this?

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 yes this is needed if we want to show Assessors a warning about being late uploading their assessment

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle ok dokey

**Comment by warrensearle** [comment]
This is done

**Comment by crablab** [comment]
@Rebecca-mcknight1991 :tada: :blush:
