### ISSUE TITLE
Normalised email value in `asesssments` collection

### ISSUE THREAD

**Issue by crablab** [jac-uk/digital-platform#336]
Email addresses are not case sensitive. We are relying on them for matching a user against a record and we need a guaranteed `strtolower` version in Firestore to compare a supplied `strtolower` version which has been used to login. 

This is a bug that is currently exists, although I'm not sure how many people it will impact since most people assume emails to be case sensitive. 

We need to: 
- [ ] Add the `emailNormalised` field for all new `assessments` 
- [ ] Backfill this field on all previous assessments (as switching is a breaking change)

**Comment by warrensearle** [comment]
Closing this issue as not needed. See comments in assessments#55.
