### ISSUE TITLE
Populate application records with diversity data

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#419]
We need to ensure diversity stats are copied across to the `applicationRecords` documents for each existing exercise.

There are two requirements here:

1. Ensure new `applicationRecords` include the diversity stats
2. Ensure existing `applicationRecords` are updated to include diversity stats

**Comment by warrensearle** [comment]
This is blocking admin#930 from being tested

**Comment by warrensearle** [comment]
The groundwork has been done for this. We have a nodeScript called `addDiversityToApplicationRecords` which can be manually run to do that!

It will be needed for QTs Results epic however have removed from the Statistics epic (admin#849) as it is no longer a requirement there.

When working on QT Results we will implement best way to ensure application records have up to date diversity data

**Comment by JeremykJAC** [comment]
Speak with Warren

**Comment by warrensearle** [comment]
See PR #604 for additional discussion
