### ISSUE TITLE
Purge backups after 30 days

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#473]
Our backups for firestore and authentication data are saved in firebase storage. At present we are not removing old backups. Our storage requirements are therefore growing daily.

This task is to create a scheduled function to delete backups when they are 30 or more days old.

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.

**Comment by KateMJAC** [comment]
Hello @warrensearle is it possible to get an update on this ticket?
