### ISSUE TITLE
Cloud function to import scenario test scores

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#482]
## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## Risk - how likely is this to impact other areas?
🟢 Low risk 

## Additional context

**Comment by KateMJAC** [comment]
Discussed as part of the QT II epic today. It was agreed that this ticket was a priority to be included in April's work.

**Comment by JeremykJAC** [comment]
After feedback in the Standup this issue is now on hold

**Comment by KateMJAC** [comment]
@HalcyonJAC  Based on discussions at the 02/07/21 Digital Stan-up, we will not need to continue with this work due to Dries work on the Merit list and UI to enter scored directly onto the platform.
