### ISSUE TITLE
Google Docs version of Panel view

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#491]
This task focuses on creating the content for a google docs version of the panel view. 

* PLEASE SEE COMMENTS BELOW *

'Starter for 10' code is available here:
https://github.com/jac-uk/digital-platform/blob/master/nodeScripts/google-docs.js

This grabs an existing `application` from firestore and outputs data to the following Google Doc:
https://docs.google.com/document/d/10e-mWyfN8_hi_-ealc6wib3kyy_MzmpB102zKOqC2U8/edit

To run the starter code run the following command from the root of the `digital-platform` project:
```
npm run nodeScript google-docs.js
```
This will append content to the Google Doc.

Note: If you don't already have it you may need to grab the `service-account.json` file and store it in the root of your local copy of the digital platform repo. Speak to @warrensearle @lloback or @tomlovesgithub 

Your mission, should you choose to accept, is to configure the document content so instead of looking like this (current content):
![Screenshot 2021-01-27 at 00.50.37.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/ac23dcf6-27cb-4c51-a916-c2c508e5d595)
It looks a lot more like this (panel view in admin):
![Screenshot 2021-01-27 at 00.49.41.png](https://images.zenhubusercontent.com/5e412648a39708a606c962c9/5e5c45c2-cb0a-4cec-8455-ea6e66e2c67f)

The following resource will be useful (as well as google search):
https://googleapis.dev/nodejs/googleapis/latest/docs/index.html

**Comment by warrensearle** [comment]
**Note**
We changed tack on this task as Google **Docs** API is a bit low-level for our needs. At least on first appearance.

We decided to generate a html string instead as we can take advantage of the Google **Drive** API to upload the html and convert it into a google doc. This is much simpler and satisfies our needs.

**Comment by tomlovesgithub** [comment]
- application list
{{ applicationReferenceNumber }} / candidate name
Personal details
Character information
Equality and diversity information
Part Time Working Preferences
Location preferences
Jurisdiction preferences
Welsh posts
Additional Preferences
Qualifications
Memberships
Experience
Post-qualification experience
Judicial experience
Gaps in employment
Reasonable length of service
Independent assessors
Additional selection Criteria
Uploaded statement of suitability
Self Assessment
CV
covering letter
Issues
Notes
Agency Report 

- panel pack list

Application Reference Number
Welsh posts
Additional Preferences
Qualifications
Memberships
Experience
Post-qualification experience
Judicial experience
Gaps in employment
Additional selection Criteria
