### ISSUE TITLE
Update fields included in Export Exercises Data

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#518]
Following feedback from the statistics team we need to format the data that's exported via the `exportExerciseData` callable function. A number of updates including:

- Dates should be in YYYY-MM-DD format
- Qualifications should be in the following format:
  ```
Qualification Type: #TYPE#, Qualification Date: #DATE#, Qualification Location: #LOCATION#,
Qualification Type: #TYPE#, Qualification Date: #DATE#, Qualification Location: #LOCATION#,
Qualification Type: #TYPE#, Qualification Date: #DATE#, Qualification Location: #LOCATION#,
  ```
- All other fields should be text output

**Comment by warrensearle** [comment]
Feedback from 22/03/2021: Disability should be yes or no. Further detail is not needed.

**Comment by warrensearle** [comment]
To Test:

- Log into Admin
- Navigate to Exercises list
- Use the checkboxes to select the exercise(s) of interest
- Click Export Data button and then Download XLSX

Expected:

An excel spreadsheet should be downloaded containing the requested data.
(see Statistics epic #849 for more information)

**Comment by KateMJAC** [comment]
Reviewed with positive results by the user testing group. I have also tested this feature with a positive result.
