### ISSUE TITLE
Recording feedback against candidates on the platform

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/digital-platform#645]
Does a candidate have more than one feedback entry on an exercise?

**Comment by joy-ade** [comment]
@mbrookeswebdev Note l have written acceptance criteria for this task because l want you to do discovery and come up with the best approach to build this functionality.

**Comment by mbrookeswebdev** [comment]
If information we need to record is a flag to indicate whether candidates received feedback or not, we could do it in a similar way I've done the Character Checks functionality, where teams could select multiple candidates and mark them as 'Feedback received'. Then in the Candidate->Applications view we can include another column where feedback status is recorded (see screenshots below). 

![Feedback1.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/9ac21265-af35-4200-93b5-f983b35aceba)
![Feedback2.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/56ee9ee3-c1f4-4cbe-aac7-3fe17ab959ea)

**Comment by joy-ade** [comment]
@mbrookeswebdev Thanks for the feedbacks, we await Matt confirmation in order to procced with this ticket.

**Comment by joy-ade** [comment]
@mbrookeswebdev the requirement for this issues has been confirmed by Matt and updated.

**Comment by warrensearle** [comment]
This ticket needs tidying up. The initial designs have been created however the ticket description and comments are messy and confusing. [ TODO either tidy this ticket or create a fresh ticket to replace it ]
