### ISSUE TITLE
Increasing the memory capacity for Qualifying Test

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/digital-platform#656]
**The Why**

There was an issues activating test for exercise DDJ 066 which had 2764 candidates for each situational Judgement  and critical analysis test. The platform couldn't activate all the 2764 tests.

After investigation we realised the default setting for processing tests was set at 2000. We would need to allocate more memory for 2000+ tests. ![image (11).png](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/bbe2533b-1a4b-43ac-b620-35480fd163cb)

**The Action**
We need to permanently increase the limit of the default setting to process 5000 tests per user for each test. The platform should be able to successfully activate 5000 candidates for each test.

We need to allocate more memory to the cloud functions so that this action can be process successfully.  Can we test and ensure that the platform can successfully activate 10,000 test

**Comment by HalcyonJAC** [comment]
Writing a note on this ticket - we currently have an 8GB limit on function invocation on google cloud which is a hard limit, and unable to be increased further. I'm looking at a way to chunk these to only process 1000 at a time, so that this function should be able to handle it.

**Comment by warrensearle** [comment]
As discussed this task is more about generating test data we can use to test QTs (and other functions) so we gain confidence that the platform will handle large amounts of data.

We are looking to ensure the platform handles an exercise with 10,000 candidates, applications and tests.

Our cloud functions have recently been manually allocated more memory than they need (8GB). In reality they need a lot less than this. Originally they were allocated 128MB which was sufficient to handle 2000 candidates but no more. So would expect ~1GB to be more than enough.

An example of allocating memory is here:
https://github.com/jac-uk/digital-platform/blob/develop/functions/callableFunctions/exportExerciseData.js#L9

Functions docs are here:
https://firebase.google.com/docs/functions/manage-functions

Firebase pricing info is here:
https://cloud.google.com/functions/pricing

**Comment by warrensearle** [comment]
Re-assigned to @warrensearle (that's me that is!)

**Comment by warrensearle** [comment]
Closing as this has been completed on the new QT platform
