### ISSUE TITLE
Re-name of DNF/out of time for  QT Test

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/digital-platform#657]
**Th Why**
 We need to re-name the terminology  used for candidates that have their test auto submitted after their time in the time  has expired. The Administrators find the current terminology used which DNF/out of time a bit  confusing.![Capture.PNG119.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/80e0d9a4-7a1e-41a9-8ca5-07df86d64c4f)![Capture.PNG121.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/3b885122-3cb8-4a2c-a7e3-6bb9d1aa0003)

**The Action**
We need to re-name  DNF/out of time to **Auto-submitted** to ensure that the Administrators understand the terminology used at different stages of the test. This will also allow Administrators to better support the candidates who might be worried about their test has not been submitted. We need to make this changes on the dashboard and on candidates log. See pictures attached

**Comment by warrensearle** [comment]
This is pretty straight-forward just a few places to reflect the change - admin, apply, downloads - so have estimated at 2 SPs

**Comment by joy-ade** [comment]
@warrensearle Thanks for updates
