### ISSUE TITLE
Changes to Diversity Monitoring Form question

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/digital-platform#666]
**The Why**
To allow the diversity team to monitor the success off the PAJE programme which the JDF are particularly keen to keep under review.

The diversity team are not superuser of the platform, nor need to be. They need this information  to see which candidates have actually completed the course and which have just watched the videos that are available to everyone. 

**The change we need to make is to this question:** 

**Have you taken part in the Pre-application judicial education programme (PAJE)?**
The PAJE scheme helps under-represented groups develop their understanding of the role
and skills of judges.
Yes
No
Prefer not to say
Save and continue
We need to change this to:

**The Expected**

**Have you taken part in the Pre-application judicial education programme (PAJE)?**
The PAJE scheme helps under-represented groups develop their understanding of the role
and skills of judges.
Yes – online resources and judge-led discussion group course
Yes – online resources only
No
Prefer not to say

**User story**

As an Administrator I want to make change to one of the diversity monitoring form question so that l can monitor the success off the PAJE programme.

**Acceptance criteria ☑️**
As a user, of the platform l want the platform to display the new changes on  the diversity monitoring form question.

**Comment by warrensearle** [comment]
Estimated at 2 SPs as this involves changing a yes/no field to have two yes options and a no... so needs a bit of consideration.
