### ISSUE TITLE
Virus scanning - scan existing files

### ISSUE THREAD

**Issue by HalcyonJAC** [jac-uk/digital-platform#696]
The virus scanner scans new files that are uploaded but files that were uploaded before the virus scanning went live have not been scanned for viruses.

- [ ] Create an endpoint that will scan all existing files for viruses
- [ ] Schedule a task to execute the above once a week at 02:00 on Sundays

**Comment by andrew-isaac** [comment]
@HalcyonJAC - Could you give me an update on the progress of this?

**Comment by JeremykJAC** [comment]
Will be complete w/e 6th May

**Comment by andrew-isaac** [comment]
Please see ticket #1393 for further updates
