### ISSUE TITLE
Unfiltered File Uploads

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#749]
The [ITHC](https://drive.google.com/drive/folders/1WFno3JjS0eG93YFY6rFpNiYs9WLlMnl6) identified that file uploads/downloads are not checked for viruses such that it was possible to upload an example virus file via Apply and for that file to be downloaded via Admin.

Work on the virus scanner should now have been completed so we need to test that our solution is working correctly on develop, staging and production environments.

**Test steps**

Use the [EICAR file](https://www.eicar.org/download-anti-malware-testfile/)

**1. Upload a file via Apply**
e.g. here we are applying for an exercise and have uploaded an infected file via the Self Assessment form
![Image](https://user-images.githubusercontent.com/8524401/182404971-2a747708-9718-4bae-a6cd-716db09c7a3f.png)

**2. Attempt to download the file via Admin**
e.g. here we have located the application created in step 1 and are trying to view the file
![Image](https://user-images.githubusercontent.com/8524401/182406323-0ad62fb0-69dc-434e-b712-eb2a2050a6a8.png)

We need to check that either:
 - the infected file cannot be uploaded, or
 - the infected file cannot be downloaded

**Comment by tomlovesgithub** [comment]
[test and results here](https://docs.google.com/spreadsheets/d/13OIlqN453-VbnBgQgcHdr_oC4AtT_LSmxqsQQnkTE80/edit?usp=sharing)

**Comment by warrensearle** [comment]
This looks great Tom, just a few simplifications to make to the test script as discussed.
Can you get this scheduled so the test is manually played each quarter?
Can you think about how we might have an automated test in addition?

**Comment by tomlovesgithub** [comment]
Hey @andrew-isaac, the other devs and i are content with this format, could i set up a call to go through this with you and discuss how we can implement this as either an automated or a maintenance task?
