### ISSUE TITLE
Monitor the uptime of our sites and alert us if a site goes down

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#750]
There have been a number of occasions where our users have been first to inform us our sites have stopped working.

Here we are looking to introduce an external uptime monitoring service which will alert us immediately if any of our sites go down.

Note that here we are purely looking at whether a site is live or not. Functionality & 'smoke' tests will be covered separately.

We have considered using:
 - Pingdom
 - Pingdom via MoJ shared account
 - Freshping

Freshping serves our purpose well and is free. To complete setup and close this ticket we need to configure freshping to:
 - [x] Monitor our main website (production)
 - [x] Monitor Apply site (production)
 - [x] Monitor Assessments site (production)
 - [x] Monitor Admin site (production)
 - [x] Monitor Apply site (staging)
 - [x] Monitor Assessments site (staging)
 - [x] Monitor Admin site (staging)
 - [x] Send email alerts to digital team
 - [x] Send slack alerts to our status/alerts channel

**Comment by andrew-isaac** [comment]
@warrensearle  - What is the progress of this ticket?

**Comment by warrensearle** [comment]
We are trying out a free tool called freshPing and it looks to cover everything we need.
I have updated this ticket accordingly and the plan is to complete the setup / rollout this month (dec 2022).

**Comment by warrensearle** [comment]
@nickaddy can you help @tomlovesgithub authorise the following email address:
jacdigital@judicialappointments.gov.uk

**Comment by nickaddy** [comment]
@warrensearle Unsure what is required here? Can confirm an email has been received to the Digital inbox:

[Freshping] tom.russell@judicialappointments.digital added you as a contact in a Freshping account
