### ISSUE TITLE
Sentry

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#756]
This task is to triage all the issues in sentry identifying any valid recurring bugs and clearing out (or ignoring) the stale or irrelevant ones.

~We are not fixing or deeply investigating any bugs as part of this ticket/effort, just generating tickets for those we need to address and deleting/ignoring those we don't.~ We have kept this ticket alive to track fixes to the bugs identified.

**Comment by HalcyonJAC** [comment]
# Error found in Sentry
Environment: production
Time range: 14D (05.09.2022 - 22.08.2022)

## admin (production 14D)

1. [Error (NotAllowedError: Read permission denied.)](https://sentry.io/organizations/judicial-appointments-commissi/issues/3167413144/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d) 
    /exercises
    
2. [UnhandledRejection (Non-Error promise rejection captured with value: Timeout)](https://sentry.io/organizations/judicial-appointments-commissi/issues/3023112874/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d) 
    /reports/handover
    
3. [TypeError (Cannot read properties of undefined (reading 'queryRef'))](https://sentry.io/organizations/judicial-appointments-commissi/issues/3425820470/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d)
    @jac-uk/jac-kit/components/Table/tableQuery.js
    ./src/store/stage/review.js
    
4. [TypeError (Cannot read properties of undefined (reading 'fullName'))](https://sentry.io/organizations/judicial-appointments-commissi/issues/3363395693/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d)
    ./src/views/Exercise/Applications/AgencyReport.vue
    
5. [TypeError (Cannot read properties of null (reading 'rolePermissions'))](https://sentry.io/organizations/judicial-appointments-commissi/issues/3555846863/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d)
    ./src/views/Exercise/Tasks/PanelsView.vue  
    ./src/views/Exercise.vue
    ./src/views/Exercise/Applications/List.vue
    ./src/views/Exercise/Applications/Application.vue    
    ./src/views/Exercise/Tasks/IndependentAssessments.vue    
    ./src/views/Candidates/CandidatesView.vue
    
6. [Error (NotAllowedError: Document is not focused.)](https://sentry.io/organizations/judicial-appointments-commissi/issues/3222698811/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d)

7. [TypeError (Cannot read properties of undefined (reading 'forEach'))](https://sentry.io/organizations/judicial-appointments-commissi/issues/3552194680/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d)
    /exercise/27XRfjOU65Nd1enzLsLt/reports/qualifying-test-reports/8SPLdGliUHx4ENbX4z7O/
    
8. [TypeError (Cannot read properties of undefined (reading 'includes'))](https://sentry.io/organizations/judicial-appointments-commissi/issues/3265883752/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d)
    ./src/store/stage/review.js
    
9. [NavigationDuplicated: Avoided redundant navigation to current location: "/exercise/V436uo3lkXVrwSt8yK7u/details/timeline/".](https://sentry.io/organizations/judicial-appointments-commissi/issues/3547879160/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d)

10. [FirebaseError: Missing or insufficient permissions.](https://sentry.io/organizations/judicial-appointments-commissi/issues/3145030033/?environment=production&project=1792541&query=is%3Aunresolved&statsPeriod=14d) 
    /exercises
    
## apply (production 14D)

1. [TypeError: Cannot read properties of undefined (reading 'length')](https://sentry.io/organizations/judicial-appointments-commissi/issues/2848860508/?environment=production&project=1499367&query=is%3Aunresolved&statsPeriod=14d)  
    ./src/views/Apply/FinalCheck/GapsInEmployment.vue
    
2. [TypeError: Cannot read properties of undefined (reading 'fullName')](https://sentry.io/organizations/judicial-appointments-commissi/issues/3524910187/?environment=production&project=1499367&query=is%3Aunresolved&statsPeriod=14d)  
    src/views/Apply/Assessments/SelfAssessmentCompetencies.vue in logEventAfterSave
    
## assessment (production 14D)

1. [UnhandledRejection: Non-Error promise rejection captured with value: Timeout](https://sentry.io/organizations/judicial-appointments-commissi/issues/3260094252/?project=5301649&query=is%3Aunresolved&statsPeriod=14d) 
    AppCheck: Fetch server returned an HTTP error status. HTTP status: 400.
    
2. [FirebaseError: Missing or insufficient permissions.](https://sentry.io/organizations/judicial-appointments-commissi/issues/3542334734/?project=5301649&query=is%3Aunresolved&statsPeriod=14d)

**Comment by andrew-isaac** [comment]
@HalcyonJAC  - Is there elements that need to be completed. Would it better to break down the tasks into smalled tickets?

**Comment by warrensearle** [comment]
@andrew-isaac this is the task that we agreed all devs would swarm on for one day... that day hasn't happened yet so today we agreed to calendar it for Friday 9th December.

**Comment by warrensearle** [comment]
> @HalcyonJAC - Is there elements that need to be completed. Would it better to break down the tasks into smalled tickets?

Some of these issues have been fixed already anyway. We will double check plus include any newer issues that haven't been dealt with.

**Comment by warrensearle** [comment]
We swarmed on this for one day and resolved 11 issues. Closing this ticket.
