### ISSUE TITLE
Use local emulator suite

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#794]
Enable digital platform and apps to run locally using the Local Emulator Suite.

This will speed up development time and enable more useful testing.

**Comment by andrew-isaac** [comment]
@warrensearle - Can you provide some background on this and who in the JAC authorise development days to be used on this task?

**Comment by warrensearle** [comment]
Hey @andrew-isaac 

Sure, here I have completed work so that we can speed up development of a number of current tasks. It is more like a day than days that have been spent. The budget for this use of development time could come out of the maintenance days we are commissioned for each month. That said I would argue that the small amount of time spent on this has already saved more time on the current tasks in hand.

Using the local emulator suite is beneficial for tasks / features which span more than one repository. In particular where a feature involves changes to our back end `digital-platform` code as all changes are 'hot loaded' locally so we can develop and test instantly. Without the local emulator we need to do more development and/or wait for changes to be deployed before we can test... which can lead to a lot of time wasted deploying and/or simulating calls to our back end.

The emulator suite also means we can have fixed starting points with our data and easily roll back to those starting points. This also saves developer time as we can test out functionality, making changes to data, and rather than having to manually undo those data changes in order to test again (or, for example, creating another new exercise to test with) we can quickly roll back and go again.

As well as saving developer time this work has the following potential benefits, each of which we will of course put proposals forward for and won't be started until approved:

 - **User testing**. Preview URLs to versions of the platform running on local emulator suite can be shared with users and testers. This can be a great way to test bigger features without impacting our live environments and also greatly saving testers time as we can provide them specific starting points for the data and they can easily roll back. So testers can focus on the features(s) being tested rather than setting up data in order to start testing.
 - **Business continuity**. Whilst not advised/promoted it is possible to load a backup of our production data into the emulator. This can be run on a virtual (or physical) machine and so means the digital platform could continue to operate completely separately from google cloud / firebase. e.g. If for some reason google went down we could be back up and running using our own servers or servers from any provider (aws, azure etc).
 - **Automated end to end testing**. End to end tests can be tricky to get right as they will typically leave a footprint in the data and be quite resource intensive. Emulator suite can again help here as we can spin up an instance of our platform and easily roll back to a known data state.

We can discuss further but hope the above helps explain this work so far.
