### ISSUE TITLE
Cloud Firestore Database

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/digital-platform#870]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/idh28n/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/idh28n/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/idh28n/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#2979FF" vlink="#954F72" style='tab-interval:36.0pt;
word-wrap:break-word'>

<div align=center>

Hello Andrew,   We are writing to let you know that   starting June   22, 2023, Cloud Firestore default database will be   represented by "(default)" in the authorizationInfo.resource field of Cloud Audit Log.   What do you need   to know?   The current database you're using   has a name called "(default)". Originally the default database was represented as an empty “” string in audit log authorizationInfo.resource, but this is inconsistent with the current pattern to use the   “(default)” string.    Before update:"authorizationInfo": [      {        "resource": "projects/my-project/databases/", # Inconsistent value        "permission": "datastore.entities.update",        "granted": true,        "resourceAttributes": { # sent for Conditional IAM          name:  "projects/my-project/databases/(default)",          type:  "firestore.googleapis.com/Database",          service: "firestore.googleapis.com",        }      }    ],After update:"authorizationInfo": [      {        "resource": "projects/my-project/databases/(default)", # Corrected value        "permission": "datastore.entities.update",        "granted": true,        "resourceAttributes": { # sent for Conditional IAM          name:  "projects/my-project/databases/(default)",          type:  "firestore.googleapis.com/Database",          service: "firestore.googleapis.com",        }      }    ],   What do you need   to do?   If you have systems that make use   of the Firestore Audit Logs and depend on the authorizationInfo.resource field in the log entry, please accommodate for the corrected   value. Any aggregation pipelines that categorize by resource may break from   this change. Learn more and gain visibility on Cloud Audit Logs.   Thanks for choosing Firestore.
--

</div>

</body>

</html>
Hello Andrew,
We are writing to let you know that starting June 22, 2023, Cloud Firestore default database will be represented by "(default)" in the authorizationInfo.resource field of [Cloud Audit Log](https://notifications.google.com/g/p/ACUgQrEzeg01YqW_NhbZLumRJbUT-ymLdDR51w1zrRKtoGH-UZPkCxzGVnP42fP3huNRIjRNIUwIwd9X_Sz6zGgtReTkO9uUHSiRtftFiaOqlelPhU9PsdCBTYd6L14tAgFkcHAWCqHxFSSY5y8MQ-1SpHxZNJkFBKJIH3Lex-l7ZhZGYHeMhSbOX3GDZSgaPVxIfZcOUNjH_6sknRSvcPO7_4CzoQBMWTbUxi3bAeIobAAy0lg).
What do you need to know?
The current database you're using has a name called "(default)". Originally the default database was represented as an empty “” string in audit log authorizationInfo.resource, but this is inconsistent with the current pattern to use the “(default)” string.

Before update:
"authorizationInfo": [
      {
        "resource": "projects/my-project/databases/", # Inconsistent value
        "permission": "datastore.entities.update",
        "granted": true,
        "resourceAttributes": { # sent for Conditional IAM
          name:  "projects/my-project/databases/(default)",
          type:  "firestore.googleapis.com/Database",
          service: "firestore.googleapis.com",
        }
      }
    ],
After update:
"authorizationInfo": [
      {
        "resource": "projects/my-project/databases/(default)", # Corrected value
        "permission": "datastore.entities.update",
        "granted": true,
        "resourceAttributes": { # sent for Conditional IAM
          name:  "projects/my-project/databases/(default)",
          type:  "firestore.googleapis.com/Database",
          service: "firestore.googleapis.com",
        }
      }
    ],
What do you need to do?
If you have systems that make use of the Firestore Audit Logs and depend on the authorizationInfo.resource field in the log entry, please accommodate for the corrected value. Any aggregation pipelines that categorize by resource may break from this change. Learn more and gain visibility on [Cloud Audit Logs](https://notifications.google.com/g/p/ACUgQrFJ4mwMaHWwOjmFHGZ1hgg22rw-lHcDyP3FPuxXC3pau_KKN3dS9dusjkNsPt-JnEwknF3zoW4TjySQ-Ftad2Ux19vIpLgP-6Duv49SBXLxFTAEMzMy6fXTBU-QwxgRcZ7ezOBoPw6B-nD8EySZLmHms_yQSy8UJyXeebNxgKB4hhaxq1_aGedJoSZVCT_lEA).
Thanks for choosing Firestore.

![Image](https://user-images.githubusercontent.com/97609636/238588553-8755ff02-3b2c-4ac7-9c01-dcad63edbf0d.png)

**Comment by warrensearle** [comment]
@tomlovesgithub and I checked and there is no action required here
