### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/digital-platform#871]
**Background**
Google Analytics is not currently being used/utilised correctly across our platforms. Can it be set up, so we are using it and it can provide useful data/insights to the Digital Team. Initial discussions with Warren suggest that the necessary code is embedded on the platform, what remains is to 'switch it on' in Google.

**Feature(s)**
- Activate Google Analytics on Admin Production 
- Review metrics available and implement most appropriate
- Analyse metrics for useful insights
 
**MOSCOW**

- A future iteration could feature integration with Slack so that important issues are flagged to the Digital Team via a Slack Channel

**Comment by warrensearle** [comment]
Please try to access: https://analytics.google.com

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/871?planning-poker) with Zenhub @drieJAC @warrensearle @tomlovesgithub

**Comment by nickaddy** [comment]
Relevant code was embedded on Admin pages on 25/01/24; need to allow a few days for usage data to start building up and then a month or so to get some meaningful metrics.
