### ISSUE TITLE
Create new Firestore Collection for 'Raise an issue' data

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/digital-platform#946]
A new Firestore Collection needs to be created so that the data gathered from user and platform can be stored there before being passed to ZenHub for creation of new tickets.

Need to first clarify a list of all the data we are passing from modal and platform.

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/946?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub
