### ISSUE TITLE
Roll out npm audit checks to all repositories

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/digital-platform#970]
Please see admin repo for reference.

We have a check for each PR and also a scheduled (daily) check to ensure there are no vulnerabilities in our code
`npm audit --omit=dev` I think is the command.

We need to roll out the same for all repos.

- [x] Admin
- [x] Apply
- [x] Assessments
- [ ] Digital Platform
- [ ] QT Platform

**Comment by warrensearle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/970?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub

**Comment by HalcyonJAC** [comment]
I have rolled out npm audit checks to **apply** and **assessments** repositories. And there will be separate tickets for **digital-platform** and **qt**.
