### ISSUE TITLE
Digital Ticketing Comms

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/digital-platform#972]
**Background**
The user support front end has been built featuring a 'Report an issue' button on Admin, that triggers a modal with user/candidate options. The content submitted is passed to ZenHub, where a ticket is created. We now need to build the back-end, which will communicate progress of ticket resolution to users and facilitate the gathering of metrics. It appears that a GitHub repo may be necessary for metrics and for automation.

**User Story** 
As a user, I would like to be informed when my issue has been picked up and resolved so that I can complete my work.
As the Digital team, I would like to inform users to who their issue has been assigned and when it has been resolved so that they are able to continue their work asap.

**Feature(s) Description** 
See the messages panel on [Miro board](https://miro.com/app/board/uXjVMgsSPkg=/).

**MOSCOW**
Use this section to prioritise all requirements, particularly where there is an MVP solution that may be added to incrementally.
* Must have - When ticket is assigned to a Developer on the Platform Issues board, a message is triggered to the Developer in Slack (Direct message OR @developer message in Platform issues channel?) - this may require some mapping of assignee handles to Slack profiles - sample content: You have been assigned ticket #XYZ with priority high/medium/low (message includes hyperlink to ticket on ZH board)
* Must have - When Developer moves ticket on ZH board to 'In Progress', a Slack alert is triggered to the user - sample content: Your issue ticket #XYZ has been assigned to **developer name** with priority critical/high/medium/low.
* Must have - When Developer moves ZH ticket to Closed, a Slack alert is triggered to the user - sample content: Your issue ticket #XYZ has been resolved and marked as Closed.
* Must have - When ZH ticket is moved to main Platform Development board, a Slack alert is triggered to the user - sample content: Your issue ticket #XYZ relates to a larger set of issues and has been moved to the main Platform Development board. The Digital team will be in touch when issue has been resolved.
* Could have - the ticket created in ZH is allocated a label 'Admin' if request is from user OR 'Apply' if request is submitted on behalf of candidate (alternatively, ADMIN/APPLY could feature in the ticket subject line)
* Must have - the board is linked to a GH repository in order to facilitate the Metrics functionality on ZH.
* Could have - tickets moved to the 'Move to DP Board' pipeline are automatically transferred to the Backlog on the main Platform Development board (via workflows in ZH, GH repo required)

**User Testing Steps**
Standalone testing session with a group of users.

**Ticket Champion**
Nick

**Happy Story (optional/delete if not used)**
* The Digital team will be able to properly track and monitor the resolution of platform issues
* The Digital team will be able to capture metrics related to, e.g. # issues resolved, resolution time, issue trends, etc

**Sad story (optional/delete if not used)** 
It is not consolidated into a single tool, but this is acceptable as long as the cohesion between the platform, ZH and Slack works comprehensively.

**Comment by nickaddy** [comment]
@warrensearle Any thoughts on the above? We need to mull over the best medium for the comms to users: is it email or Slack message...

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/digital-platform/972?planning-poker) with Zenhub @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
> @warrensearle Any thoughts on the above? We need to mull over the best medium for the comms to users: is it email or Slack message...

The other option to consider is showing a message on the platform. So there's:
 - Email
 - Slack
 - Admin

**Comment by warrensearle** [comment]
My vote would be for Admin as this will be easier to support a conversation between user and support-person (in the future).

For an initial one-way alert then email will be slightly quicker to implement. I say that because I'm not sure (until we try) how well we will be able to target/mention specific users in our slack message.

**Comment by nickaddy** [comment]
@drieJAC Thanks for bringing me up to speed on the comms challenges. We agreed the following:

- Must have 2: instead of triggering a message to user once issue assigned, we will mention the user as well as the developer in the post to the slack channel
- Must have 3: instead of triggering a message to user once issue closed, the developer will manually inform the user in the Slack channel
- Must have 4: Omar thinks it may be possible to trigger an alert when message moved to another board
- Everything else looks good

Actions:

- @drieJAC to investigate user mapping in line with mentioning user at same time as developer in Slack channel
- @drieJAC to investigate effect on messaging of unassigning/reassigning an issue
- @drieJAC to investigate triggering message when moving to another board
- @nickaddy to investigate setting up ZH workflow to move issues between boards

**Comment by drieJAC** [comment]
@drieJAC to investigate user mapping in line with mentioning user at same time as developer in Slack channel - DONE
@drieJAC to investigate effect on messaging of unassigning/reassigning an issue - Unassigning will not call Slack unless we want it to!

**Comment by drieJAC** [comment]
To obtain the reporter's slack user ID we will add an input to the form to gather this information the first time they raise an issue. After that it will be stored against their user profile.

**Comment by nickaddy** [comment]
@drieJAC Should the pull requests #999 and #2279 be linked to this ticket?

**Comment by drieJAC** [comment]
Need to add check for Github security key when GH webhook is makes an inbound call.
